spring:
  mvc:
    dispatch-options-request: true
  datasource:
    url: jdbc:mysql://localhost:3306/?user=root
    username: root
    password: 123456az
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:mybatis/mappers/*.xml

