spring:
  mvc:
    dispatch-options-request: true
  datasource:
    url:jdbc:mysql://localhost:3306/?user=root
    username: root
    password: 123456az
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      aop-patterns: com.example.demo*  #监控SpringBean
      filters: stat,wall     # 底层开启功能，stat（sql监控），wall（防火墙）

      stat-view-servlet:   # 配置监控页功能
        enabled: true
        login-username: admin
        login-password: admin
        resetEnable: false

      web-stat-filter:  # 监控web
        enabled: true
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'


      filter:
        stat:    # 对上面filters里面的stat的详细配置
          logSlowSql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false

mybatis-plus:

  mapper-locations: classpath:mybatis/mappers/*.xml
  configuration:
    log-impl=org:
      apache:
        ibatis:
          logging:
            stdout:
              StdOutImpl
  global-config:
    db-config:
      logic-delete-value=1
      logic-not-delete-value=0
servlet:
  multipart:
    enabled: true